### ISSUE TITLE
PolyTracker taint coverage example

### ISSUE THREAD

**Issue by cponcelets** [trailofbits/polytracker#6396]
Dear PolyTracker Team,
I tried to use your amazing tool for extracting program BBs touching tainted data.
(I think) I managed to print the functions and corresponding BBs involved into tainted contexts,
and have a program (sub)trace of tainted BB's Ids.

However, I would like to have an output in line of code coverage.
(Notice that I don't want to process further-using PolyFile-since I do not want to analyze grammars)

**Is there a conversion or output feature that can give the approximated line of code corresponding to a BasicBlock Id?**

---

Furthermore, I tried some (maybe too) tiny C examples in order to have simple working cases.
Unfortunately, I could not manage to get tainted traces from those.
Is there a minimal requirement for the tainted algorithm to detect taint accesses?

Best

**Comment by carsonharmon** [comment]
Hey! Thank you for your interest, we would be happy to help you. 

We don't have a conversion our output feature to get the lines of code related to basic blocks, but I've done this before and could add it to Polytracker for you :) 

Can you post your C examples? It should pick up the taint, if its buggy I will fix it for you. 

Thanks,
Carson

**Comment by cponcelets** [comment]
> We don't have a conversion our output feature to get the lines of code related to basic blocks, but I've done this before and could add it to Polytracker for you :)

That would be wonderful! (and used a lot)

> Can you post your C examples? It should pick up the taint, if its buggy I will fix it for you.

After testing again, I figured out that a warning was printed (I was using the fopen,fscanf, and fclose functions).
So I changed for the old good read and it worked :)
Excuse me for that.

That bring me to another question, I see 'call to uninstrumented function bcmp' while I am running an instrumented real software. However, I saw a checked box in #6342 for bcmp, is this for the next release?

**Comment by carsonharmon** [comment]
fopen and fread SHOULD work, we have tests for it in the `test_fopen.c` file. Can you try running the tests on your machine with `pytest` to see if things are working? 

bcmp, good catch! We should have it, its actually inside of dfsan (which we build off of). Its most likely saying its uninstrumented because of a mistake in an ABI list. 

You could most likely fix it now by setting 
fun:__gcc_bcmp=uninstrumented
fun:__gcc_bcmp=custom
fun:bcmp=uninstrumented
fun:bcmp=custom

but i did think this was already fixed since its currently marked as functional. Do you have a test you could provide so I could reproduce the warning? 

Thanks

**Comment by cponcelets** [comment]
Yes, here [pytest.output.txt](https://github.com/trailofbits/polytracker/files/7269288/pytest.output.txt) are the outputs from pytest. I am using the docker image but the host has the following uname -a output:

```
Linux 2434bd74d240 4.15.0-99-generic #100~16.04.1-Ubuntu SMP Wed Apr 22 23:56:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Notice that, though the failures, `test_fopen.c` worked.

---

For the bcmp test I can try to do one, but I ll need to shorten the code.

**Comment by carsonharmon** [comment]
Something looks very wrong! 

Are you potentially using an older version of polytracker by any chance? 

I see warning messages like "Could not resolve the function entry associated with X", and I don't believe that code is within the codebase anymore.

**Comment by cponcelets** [comment]
It is a good question, I followed the README instructions, running:

```
pip3 install polytracker
polytracker docker pull
polytracker docker run
```

`polytracker -v` returns `3.0.1` in the docker container.

---

I ran `pip3 install --upgrade polytracker pysqlite3` which installed some newer versions but did not solve any issues.
Maybe the Dockerfile should be updated.

**Comment by carsonharmon** [comment]
Gotcha, can you try pulling the repo and doing this from the home dir? 

```
pip3 install .
polytracker docker rebuild 
pytest
```

and tell me if that fixes anything? 

Thanks

**Comment by carsonharmon** [comment]
Hmmmm thats interesting! 

@ESultanik any ideas here? 

@cponcelets would you be interested in getting on a google meet sometime? I can help you debug live maybe

**Comment by cponcelets** [comment]
Yes, of course if it helps.

**Comment by carsonharmon** [comment]
We install gclang in the dockerfile, but for some reason it sounds like this might be executing on your host machine instead of Docker? That is strange, we are still looking into this. Im confident that eventually we will find a solution.

**Comment by cponcelets** [comment]
Yes, it works like a charm. 
(Except a warning about importation.)

Here is the pytest outputs for completion, thank you very much.
[pytest-output.txt](https://github.com/trailofbits/polytracker/files/7354628/pytest-output.txt)
